In [3]:
import pandas as pd 
data = pd.read_excel("analyse de terre.XLSX")
data

,Réf_échantillon,Argile,Limon Fin,Limon Grossier,Sable Fin,Sable_Grossier,pH_eau,Carbonates_totaux,Carb_organique,Matière organique,Azote total,C/N -,P2O5 Olsen,Cu DTPA mg/kg,Zn DTPA mg/kg,Ni DTPA mg/kg,Cu total ER (mg/Kg),Ni total ER (mg/Kg),Pb total ER (mg/Kg),Zn total ER (mg/Kg)
0,EvEx_03Gal,557,189.0,104.0,91.3,58.8,8.3,225.0,31.6,54.6,2.30,13.9,0.026,13.1,4.7,0.37,71.2,26.2,44.9,109.0
1,EvEx_04Mou,362,123.0,125.0,196.0,194,8.3,101.0,16.1,27.9,1.20,12.9,0.057,5.6,2.9,0.89,38.4,79.6,36.1,91.4
2,EvEx_05Mou,205,116.0,125.0,245.0,309,8.1,94.4,21.1,36.5,1.70,12.1,0.095,3.3,9.5,0.69,31.4,61.3,70.7,122.0
3,EvEx_06Lou,405,135.0,130.0,253.0,77.6,8.5,207.0,15.1,26.1,1.10,13.7,0.027,16.4,3.2,0.26,70.3,29.1,47.6,77.0
4,EvEx_07Lou,431,135.0,128.0,253.0,54.0,8.4,156.0,13.2,22.8,1.00,13.2,0.058,16.6,3.1,0.16,77.1,33.6,52.0,85.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,CpUt_16Rob,316,147.0,135.0,190.0,211,8.5,494.0,27.4,47.4,1.40,20.0,0.026,7.6,3.2,0.60,24.4,15.7,16.4,35.1
128,CpUt_17Rob,314,129.0,86.0,178.0,293,8.6,433.0,21.4,37.0,1.20,17.8,0.014,6.9,4.0,0.44,34.7,41.6,19.5,47.1
129,CpUt_18Rob,378,130.0,121.0,188.0,183,8.7,730.0,12.1,21.0,0.97,12.6,0.028,5.0,2.5,0.35,14.2,9.9,7.8,21.4
130,CpUt_19Sun,257,102.0,129.0,272.0,241,8.6,349.0,10.7,18.5,1.40,7.8,0.009,8.6,4.4,0.22,29.5,14.5,24.1,41.9
131,CpUt_20Cas,223,119.0,110.0,317.0,231,8.6,393.0,12.7,22.0,1.30,9.9,0.017,12.4,1.8,0.27,44.1,12.7,17.8,28.9

In [4]:
# Remplacement des points par des virgules dans les colonnes numériques
# Conversion en chaîne pour permettre le remplacement
data_modif = data.applymap(lambda x: str(x).replace('.', ',') if isinstance(x, (int, float, str)) else x)

# Sauvegarde du fichier modifié
#data.to_excel('analyse de terre.xlsx', index=True)

C:\Users\Ndiaye\AppData\Local\Temp\ipykernel_65864\3346703750.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data_modif = data.applymap(lambda x: str(x).replace('.', ',') if isinstance(x, (int, float, str)) else x)

In [5]:
data_modif

,Réf_échantillon,Argile,Limon Fin,Limon Grossier,Sable Fin,Sable_Grossier,pH_eau,Carbonates_totaux,Carb_organique,Matière organique,Azote total,C/N -,P2O5 Olsen,Cu DTPA mg/kg,Zn DTPA mg/kg,Ni DTPA mg/kg,Cu total ER (mg/Kg),Ni total ER (mg/Kg),Pb total ER (mg/Kg),Zn total ER (mg/Kg)
0,EvEx_03Gal,557,"189,0","104,0","91,3","58,8","8,3","225,0","31,6","54,6","2,3","13,9","0,026","13,1","4,7","0,37","71,2","26,2","44,9","109,0"
1,EvEx_04Mou,362,"123,0","125,0","196,0",194,"8,3","101,0","16,1","27,9","1,2","12,9","0,057","5,6","2,9","0,89","38,4","79,6","36,1","91,4"
2,EvEx_05Mou,205,"116,0","125,0","245,0",309,"8,1","94,4","21,1","36,5","1,7","12,1","0,095","3,3","9,5","0,69","31,4","61,3","70,7","122,0"
3,EvEx_06Lou,405,"135,0","130,0","253,0","77,6","8,5","207,0","15,1","26,1","1,1","13,7","0,027","16,4","3,2","0,26","70,3","29,1","47,6","77,0"
4,EvEx_07Lou,431,"135,0","128,0","253,0","54,0","8,4","156,0","13,2","22,8","1,0","13,2","0,058","16,6","3,1","0,16","77,1","33,6","52,0","85,5"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,CpUt_16Rob,316,"147,0","135,0","190,0",211,"8,5","494,0","27,4","47,4","1,4","20,0","0,026","7,6","3,2","0,6","24,4","15,7","16,4","35,1"
128,CpUt_17Rob,314,"129,0","86,0","178,0",293,"8,6","433,0","21,4","37,0","1,2","17,8","0,014","6,9","4,0","0,44","34,7","41,6","19,5","47,1"
129,CpUt_18Rob,378,"130,0","121,0","188,0",183,"8,7","730,0","12,1","21,0","0,97","12,6","0,028","5,0","2,5","0,35","14,2","9,9","7,8","21,4"
130,CpUt_19Sun,257,"102,0","129,0","272,0",241,"8,6","349,0","10,7","18,5","1,4","7,8","0,009","8,6","4,4","0,22","29,5","14,5","24,1","41,9"
131,CpUt_20Cas,223,"119,0","110,0","317,0",231,"8,6","393,0","12,7","22,0","1,3","9,9","0,017","12,4","1,8","0,27","44,1","12,7","17,8","28,9"

In [6]:
data_modif.dtypes

Réf_échantillon          object
 Argile                  object
 Limon Fin               object
 Limon Grossier          object
 Sable Fin               object
 Sable_Grossier          object
 pH_eau                  object
 Carbonates_totaux       object
 Carb_organique          object
 Matière organique       object
 Azote total             object
 C/N -                   object
 P2O5 Olsen              object
 Cu DTPA mg/kg           object
 Zn DTPA mg/kg           object
 Ni DTPA mg/kg           object
 Cu total ER (mg/Kg)     object
 Ni total ER (mg/Kg)     object
 Pb total ER (mg/Kg)     object
 Zn total ER (mg/Kg)     object
dtype: object

In [7]:
#pip install openpyxl