In [2]:
import pandas as pd
import numpy as np

In [21]:

df1 = pd.read_excel("../Donnees/analyse de terre.XLSX")
df2 = pd.read_excel("../Donnees/BiomasseMoleculaireMicrobienne.xlsx")
df3 = pd.read_csv("../Donnees/DataVdt_N.csv")
df4 = pd.read_excel("../Donnees/TableauxdonnéesParcelle.xlsx")

id_col_1 = 'Réf_échantillon'
id_col_2 = 'code echantillon'
id_col_3 = df3.columns[0]
id_col_4 = 'Parcelle'

df_merged = df1.merge(df2, left_on=id_col_1, right_on=id_col_2)
df_merged = df_merged.merge(df3, left_on=id_col_1, right_on=id_col_3)
df_merged = df_merged.merge(df4, left_on=id_col_1, right_on=id_col_4)

result_df = pd.DataFrame()
result_df[id_col_1] = df_merged[id_col_1]
result_df = result_df.join(df_merged[[
    ' Matière organique ', 
    ' Azote total', 
    'Moy E1_E2',  
    'somme_espece_biodiv', 
    'Ganivelles', 
    'Emplacement', 
    'Enfantsparm2'
]])

result_df.to_csv("../Donnees/excel_combiné.csv", index=False)

result_df.head()

,Réf_échantillon,Matière organique,Azote total,Moy E1_E2,somme_espece_biodiv,Ganivelles,Emplacement,Enfantsparm2
0,EvEx_03Gal,54.6,2.3,47.790480,3,1,1,14.5
1,EvEx_04Mou,27.9,1.2,40.226231,4,1,1,11.4
2,EvEx_05Mou,36.5,1.7,46.571557,4,1,1,11.4
3,EvEx_06Lou,26.1,1.1,27.663560,6,1,1,11.7
4,EvEx_07Lou,22.8,1.0,18.440070,1,0,1,11.7